# master
-
  branches:
    only:
      - master 

  version: 1.0.0

  skip_tags: true

  build:
    parallel: true
    publish_nuget: true
    verbosity: quiet

  os: Visual Studio 2017

  build_script:
    - ps: $env:BUILD_VERSION = $env:appveyor_build_version
    - ps: .\build.ps1

  artifacts:
  - path: '**\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: WPva4EB+YwQeG306yJc4hRBe99TMEJxIYf11r4kbtUkUd4F5h2J1odheapRyiwYI
    skip_symbols: true
    artifact: /.*\.nupkg/

  on_failure:
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"    
    
  on_success:
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    - ps: git config --global credential.helper store
    - ps: git config --global user.email "$($env:Git_Email)"
    - ps: git config --global user.name "$($env:Git_Username)"
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:Git_Username):$($env:Git_Password)@github.com`n"
    - ps: git tag $($env:appveyor_build_version) $($env:APPVEYOR_REPO_COMMIT)
    - git push --tags

-
  branches:
    except:
      - master

  version: 1.0.0.{build}-{branch}

  skip_tags: true

  clone_depth: 1

  build:
    parallel: true
    publish_nuget: true
    verbosity: quiet

  build_script:
    - ps: $env:BUILD_VERSION = $env:appveyor_build_version
    - ps: .\build.ps1
 
  os: Visual Studio 2017
 
  artifacts:
  - path: '**\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: WPva4EB+YwQeG306yJc4hRBe99TMEJxIYf11r4kbtUkUd4F5h2J1odheapRyiwYI
    skip_symbols: true
    artifact: /.*\.nupkg/

  on_success:
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"    
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))